### ISSUE TITLE
Protobuf Not being able to append or truncate.

### ISSUE THREAD

**Issue by NoSharp5** [OxideMod/Oxide.Core#11]
It's possible to overwrite a file and append. 
This happens when saving to an already used file.

**Comment by lukespragg** [comment]
How is this an Oxide issue? Protobuf is not from Oxide.

**Comment by NoSharp5** [comment]
This is an oxide issue as when used in protostorage you use filemode.create and not file mode.truncate

**Comment by lukespragg** [comment]
Why exactly are you trying to change the core data handling?

**Comment by NoSharp5** [comment]
I am doing it like so: Core.ProtoStorage.Save<T>(value, FileName);
on an already existing file, i would like to be able to append/overwrite.

**Comment by NoSharp5** [comment]
Fixed it. Thanks for your help
