### ISSUE TITLE
Not all oxide commands work in RCON

### ISSUE THREAD

**Issue by FireStorm78** [OxideMod/Oxide.Core#15]
Commands such as oxide.plugins and oxide.show user SteamName no longer work in RCON or the SERVER console. They do work through the game client console if the user has the oxide.* permissions. Server admins can't always have a game client open to manage their servers so it would be nice if this could be fixed.

**Comment by thibmo** [comment]
What RCON client are you using?
Do you use RCONWeb or RCONLegacy?

**Comment by FireStorm78** [comment]
Using RCON.IO which would be using the web interface.

**Comment by FireStorm78** [comment]
I do. And I just tested on a windows rust server and the commands do work on the server console. It's just RCON for me.

![image](https://user-images.githubusercontent.com/25544830/34251528-b29d1b9a-e5fd-11e7-8648-9b8886c30641.png)

**Comment by thibmo** [comment]
I also checked via rcon.io/console
The only difference is that I run Linux servers, not Windows servers.
Could you verify if the issues still persist when you overwrite the oxide files with the most recent release specific to your game?

**Comment by FireStorm78** [comment]
The issue I'm having is with a linux server hosted on Fragnet. I spun up a new linux server locally and the commands work there through rcon.io and also http://facepunch.github.io/webrcon. Suspect a potential issue with fragnet configuration?

**Comment by thibmo** [comment]
Do you have access to the local files on that server?
If so, could you attach a redacted version?

**Comment by FireStorm78** [comment]
I have access to the files. Which ones do you want to see?

**Comment by thibmo** [comment]
First the start script would do.
Also, go you use LGSM or is start/stop/watchdog done by FragNet?

**Comment by FireStorm78** [comment]
I'm not sure what Fragnet uses. I used LGSM on the linux server I spun up that worked. 

The Fragnet commandline is:
-batchmode +server.ip REDACTED +server.port 28215 +rcon.ip REDACTED +rcon.port 28217 -server.maxplayers 100 -logFile "output.txt" -server.hostname "REDACTED" -server.identity fragnet -server.worldsize 3000 -server.description "REDACTED" -server.headerimage "REDACTED" -server.url "REDACTED" +server.level "Procedural Map" +server.seed 122876 +rcon.password "REDACTED" +server.radiation false +rcon.web 1 +oxide.directory "server/fragnet/oxide"

**Comment by thibmo** [comment]
Ok.. Nothing wrong with that so far, did you set your local ports to the same as the server's?
Could be something, too.
Do the logs show anything that could indicate an exception?

**Comment by FireStorm78** [comment]
I cloned all the settings from the FragNet server to my local server. So same ports and everything. I just updated oxide again on the fragnet server because the versions are slightly different. 3771 vs 3773 on oxide.core.dll. I'll check the logs.

**Comment by FireStorm78** [comment]
Same issue but here's a strange thing. In oxide/logs/oxide_2017-12-21.txt shows the results of the commands. They just are not displayed in rcon. odd

**Comment by FireStorm78** [comment]
Command results also show in the output.log. No exceptions that I've found so far.

**Comment by thibmo** [comment]
That's just strange....
If it shows there is SHOULD show in console and RCON too

**Comment by FireStorm78** [comment]
I'm comparing files between fragnet and a windows rust server to see if there are any modified files from the steam app standard. This could be a issue with the provider modifying dlls?

**Comment by FireStorm78** [comment]
Can't reproduce the issue locally even with a complete copy of the RustDedicated_Data folder.

**Comment by thibmo** [comment]
Very dubious. I'd contact them and ask if they can have a look at this. I doubt it's on the side of Oxide.

**Comment by FireStorm78** [comment]
Agreed. I'll let you know what I find out.

**Comment by FireStorm78** [comment]
I've done a complete clone of the fragnet server to my desktop. It appears to be running on Windows based on the lack of linux pre-requisites. The only missing files are RustDedicated.exe and CSharpCompiler.exe. They must run from outside the server folder. 

When running with the latest RustDedicated.exe I have no issues with RCON and OXIDE. So it definitely appears to be something Fragnet is doing with their setup. I've logged a ticket with them to investigate. They will likely try to blame Oxide but I will try and resolve it with them. 

I'm fairly confident this is not an oxide bug anymore so I'm going to close this issue. Thanks for the help troubleshooting.

**Comment by lukespragg** [comment]
This is likely still an Oxide issue, but if your investigation doesn't warrant anything, then please open an issue under the Oxide.Rust repository or on our forums as it's not an Oxide.Core issue.
