### ISSUE TITLE
Looking for contributions?

### ISSUE THREAD

**Issue by igolden** [OxideMod/Oxide.Core#3]
Hey guys - thanks for your awesome work with Oxide. I'm new to modding, and Oxide has been a gamechanger for me.

I want to pay it forward, and contribute to the future development of Oxide. How could i help contribute to this repo or Oxide.Rust?  There's no open issues (kudos to you guys), which is normally where I would start looking for contributions. Is there a roadmap/list of issues elsewhere? Just looking for low hanging fruit I could knock out to help out.  

Thanks again - happy modding!

**Comment by lukespragg** [comment]
The old repo and current issues are here: https://github.com/OxideMod/Oxide/issues

**Comment by igolden** [comment]
Awesome, thanks @lukespragg
