### ISSUE TITLE
Plugin references not being assigned when public

### ISSUE THREAD

**Issue by jstein-dev** [OxideMod/Oxide.Core#6]
I discovered an issue, when making plugin references public they're not assigned. Below is the code I used to verify.
```csharp
[PluginReference]
private Plugin Economics;

private void OnServerInitialized() => Puts($"Economics null: {Economics == null}");
// Economics null: false
```

```csharp
[PluginReference]
public Plugin Economics;

private void OnServerInitialized() => Puts($"Economics null: {Economics == null}");
// Economics null: true
```

**Comment by austinv900** [comment]
Not really a issue. It's how it was designed.

**Comment by austinv900** [comment]
You can find what I'm talking about in the constructor https://github.com/OxideMod/Oxide.CSharp/blob/develop/Oxide.CSharp/CSharpPlugin.cs

**Comment by jstein-dev** [comment]
I still view this as an issue, there's no reason I can see as to why public fields marked with the plugin reference attribute shouldn't be assigned. It's an extreme annoyance, as a getter is needed to access the plugin from extension methods.

**Comment by austinv900** [comment]
That may be true but you would still need to some how access your plugin from the extension method also either by a static field or loading the GetPlugin method under the plugin manager. I believe you can still access plugin references if they are private by doing. YourPlugin.Call(Field name)

**Comment by austinv900** [comment]
It could be changed but I believe last time I tried to have it changed there was a specific reason

**Comment by thibmo** [comment]
IMO this is fine.
Why would you even want to make the reference public?
Every plugin should reference their own required plugins. Also, every plugin references the same instance of the required plugin.

I see no reason to make the reference public, it would be a security leak if it would be.

I made a small test case to prove that they all share the same instance:
### PlugRefTestA
```CSharp
namespace Oxide.Plugins
{
    [Info("PlugRefTestA", "ThibmoRozier", "1.0.0", ResourceId = 0)]
    [Description("Some dumb test; File A")]
    class PlugRefTestA : CovalencePlugin
    {
        public string InstanceTest { get; set; } = "Default";

        public string TestStringReturn() => "PlugRefTestA.TestStringReturn = Success";

        public void TestConsoleWrite() => Puts("PlugRefTestA.TestConsoleWrite = Success");

        public void TestInstance() => Puts("PlugRefTestA.TestInstance = {0}", InstanceTest);
    }
}
```

### PlugRefTestB
```CSharp
// Requires: PlugRefTestA

namespace Oxide.Plugins
{
    [Info("PlugRefTestB", "ThibmoRozier", "1.0.0", ResourceId = 0)]
    [Description("Some dumb test; File B")]
    class PlugRefTestB : RustPlugin
    {
        [PluginReference] private PlugRefTestA PlugRefTestA;

        void OnServerInitialized()
        {
            PlugRefTestA.InstanceTest = "Changed By PlugRefTestB";
        }

        [ConsoleCommand("reftest")]
        void PluginRefTest(ConsoleSystem.Arg arg)
        {
            string str = PlugRefTestA.TestStringReturn();
            Puts(str);

            PlugRefTestA.TestConsoleWrite();
        }
    }
}
```

### PlugRefTestC
```CSharp
// Requires: PlugRefTestA

namespace Oxide.Plugins
{
    [Info("PlugRefTestC", "ThibmoRozier", "1.0.0", ResourceId = 0)]
    [Description("Some dumb test; File C")]
    class PlugRefTestC : RustPlugin
    {
        [PluginReference] private PlugRefTestA PlugRefTestA;

        [ConsoleCommand("refinstancetest")]
        void PluginRefInstanceTest(ConsoleSystem.Arg arg) => PlugRefTestA.TestInstance();
    }
}
```

### Outcome:
![](https://image.prntscr.com/image/I7-7MdjzSBGtPkwwfDw5mQ.png)

**Comment by austinv900** [comment]
I wouldn't call it a security leak making a plugin reference public but highly unnecessary.

**Comment by thibmo** [comment]
Fair enough. :)

**Comment by lukespragg** [comment]
If you’d like to see it, feel free to open a PR. I don’t see a need for this though personally.
